### ISSUE TITLE
Compiling for ESP32 in MSYS2 environment under Windows 10

### ISSUE THREAD

**Issue by benjamind** [warmcat/lws-esp32-test-server-demos#5] opened 2017-11-06 00:12 UTC
I'm trying to compile these demos under Windows 10 in the MSYS2 environment provided by ESP-IDF.

I installed the toolchain and MSYS2 shell as described here - http://esp-idf.readthedocs.io/en/latest/get-started/windows-setup.html

This is all working fine and I'm compiling other ESP32 code. However the lws-esp32 implementation seems to require cmake to compile. This does not appear to be bundled in the MSYS2 environment distributed by ESP-IDF. Failing with the following error:

```
doing lws cmake
/bin/sh: line 2: cmake: command not found
make[2]: *** No targets specified and no makefile found.  Stop.
make[1]: *** [/d/Coding/lws-esp32-test-server-demos/components/libwebsockets/component.mk:12: build] Error 2
make: *** [C:/msys32/home/ben/esp/esp-idf/make/project.mk:435: component-libwebsockets-build] Error 2
```

Installing with `pacman -S mingw-w64-i686-cmake` gets us over that hurdle. However compilation then seems to be targetting MSVC rather than the cross compilation target:

```
$ make
doing lws cmake
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23918.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
```
At this point I'm kind of stuck, the `cmake` call in the `component.mk` seems to be doing the right thing, passing the `xtensa-esp32-elf-gcc` location for `CROSS_PATH` and setting the `CMAKE_TOOLCHAIN_FILE` to the `/contib/cross-esp32.cmake` file. But it seems to be being ignored.

Any suggestions?

**Comment by lws-team** [comment] 2017-11-06 00:42
I don't use windows for 15 years or so now.  The windows support in lws is all contributed.

So unless it's either contributed or trivial, I'm not going to spend any time on making it work with windows.

My suggestion is use linux in a vm.

Having said that... in case it is trivial... you are doing `make flash_ota monitor" in the top level of the test server project, right?  And the results from this won't be useful unless you built and flashed the -factory app first.

**Comment by benjamind** [comment] 2017-11-06 03:30
I have considered running the build under a Linux VM but that does have its own issues (file paths no longer match so IDE integration no longer works, mapped folders don't properly symlink inside linux VMs so you end up running smb shares which becomes a pain to manage across development teams, and switching wholesale to linux really isn't an option - it has the worst windowing system and mouse behaviors in existence). Besides the ESP-IDF platform manages to run under windows, to claim ESP-IDF compatibility libwebsockets should really compile under it too.

Anyway, I managed to get it to compile, mostly, by doing the following:

* add `-G'MSYS Makefiles'` to the `cmake` command  to fix this issue -https://github.com/Alexpux/MINGW-packages/issues/306
* compile `genromfs` under MSYS2 and add it to the path
* add `.exe` extension to executables referenced in `contrib/corss-esp32.cmake`
* add `-DLWS_WITH_BUNDLED_ZLIB=0` to `cmake` command to avoid automatic windows zlib bundling

This gets me to `sys/ioctl.h` not being found, further debugging seems to indicate the include paths for the `cmake` compilation are wrong as `esp_heap_caps.h` is also missing.

**Comment by benjamind** [comment] 2017-11-06 03:39
Adding the following to the `cross-esp32.cmake` fixes the missing includes:

```
	-I$(IDF_PATH)/components/vfs/include/ \
	-I$(IDF_PATH)/components/soc/include/ \
	-I${IDF_PATH}/components/heap/include \
```

This now compiles successfully. 

I'll investigate how to more legitimately add the `exe` extension in the `cross-esp32.cmake`. Currently not sure how to put build platform specific settings into cmake files so will have to investigate further.

Can you explain the `genromfs` dependency, is this a fundamental part of how `libwebsockets` work or is this just an artifact of how the resources have been packed for the factory and test apps?

**Comment by lws-team** [comment] 2017-11-06 03:53
Nice job... those three includes are needed for esp-idf to build anything here... I added them in the top-level Makefile for -factory and -test-server-demos already... it looks like CFLAGS isn't inherited the same on your setup.

ROMFS isn't part of lws, although lws has its own ROMFS parser.

It's there to enable lws on ESP32 to find assets to serve in the absence of any other filesystem.  lws has its own internal VFS and by default the ESP32 platform wires it up to the romfs, so you can serve whatever you put in ./romfs-files (which the Makefile runs genromfs on).

The ROMFS is composed on to the binary along with a JSON manifest of what the image actually is.  The factory stuff can read the manifest and confirm it's an OTA image, its name etc.

That is put together using shellscript, which is portable enough to work on eg Mac.  But not windows.

genromfs itself is foss and will work on windows https://github.com/chexum/genromfs but the problem is the shellscript I should think.

**Comment by benjamind** [comment] 2017-11-06 04:03
So was this decision made because at the time there was no filesystem on the esp32? As I understand it there is now spiffs and fatfs support in the vfs under latest esp-idf.

Just wondering if this dependency can now be removed and replaced with something more esp native.

**Comment by lws-team** [comment] 2017-11-06 04:12
Yes, but it was more

 - The partitioning is not really fixed on ESP32.  Where you VFS storage is or how much of it you want is a variable.

 - The things you serve are typically immutable or dynamic.  A ROMFS is good for immutable things.  If the VFS is writable, it can be trashed.

 - lws has its own thin "file ops" vfs

You don't have to use ROMFS, the file ops are set here by default

https://github.com/warmcat/libwebsockets/blob/master/lib/plat/lws-plat-esp32.c#L1707
https://github.com/warmcat/libwebsockets/blob/master/lib/plat/lws-plat-esp32.c#L1341

You can simply override the default fops using the same apis in user code to use provide mapping for open, read, write etc on to the ESP VFS apis.

On nice thing about the lws VFS, it knows how to serve gzip-compressed files directly from inside a ZIP file.  I have an ESP32 application here that does that (it requires stock zlib as a component, but that builds without changes).

**Comment by benjamind** [comment] 2017-11-06 16:30
I see, that makes sense.

My application will probably require a non-writeable partition and a writeable one, I guess there's nothing stopping me having the static files in the ROMFS partition and a separate FATFS partition for dynamically written files though.

I will investigate updating the genromfs scripts to work on Windows and see if I can get my changes legit so I can file a PR.

Thanks for the help!

**Comment by benjamind** [comment] 2017-11-07 07:34
I made some progress getting the compilation to work on windows but be non platform specific. Will file a PR sometime this week.

However, in trying to test it out, I flashed the factory app built with my changes above, this seemed to go well at first. Build resulted in a `lws-esp32-factory.bin` of 870kb, and a `romfs.img` of 168kb. Flashed this onto the device and it starts up with the following log:

```
4: gapss from LWS_GAPSS_INITIAL to LWS_GAPSS_SCAN
I (96) wifi: wifi firmware version: 7a658f3
I (96) wifi: config NVS flash: disabled
I (96) wifi: config nano formating: disabled
I (106) wifi: Init dynamic tx buffer num: 20
I (106) wifi: Init data frame dynamic rx buffer num: 20
I (116) wifi: Init management frame dynamic rx buffer num: 20
I (116) wifi: wifi driver task: 3ffc55e8, prio:23, stack:4096
I (126) wifi: Init static rx buffer num: 20
I (126) wifi: Init dynamic rx buffer num: 20
I (126) wifi: Init rx ampdu len mblock:7
I (136) wifi: Init lldesc rx ampdu entry mblock:4
I (136) wifi: wifi power manager task: 0x3ffce924 prio: 21 stack: 2560
I (166) wifi: mode : sta (24:0a:c4:04:be:f8) + softAP (24:0a:c4:04:be:f9)
4: SYSTEM_EVENT_STA_DISCONNECTED
4: gapss from LWS_GAPSS_SCAN to LWS_GAPSS_SCAN
4: No SSL certs... using port 80
4:  mem: platform fd map:   120 bytes
4: ROMFS length 168KiB
{
 "schema": "lws1",
 "model": "lws",
 "builder": "BEN-DESKTOP",
 "app": "lws-esp32-factory",
 "user": "ben",
 "git": "3f93751-dirty",
 "date": "Mon, Nov  6, 2017  7:13:50 PM",
 "unixtime": "1510024430",
 "file": "lws-esp32-factory-1510024430.bin",
 "factory": "y"
}
4: Creating Vhost 'ap' port 80, 3 protocols, IPv6 off
4: SYSTEM_EVENT_SCAN_DONE
4: scan_finished: count 0
4: setting mount default to factory
4:  heap :190004 (-4964)
4:  heap :189924 (-80)
4: SYSTEM_EVENT_SCAN_DONE
4: scan_finished: count 7
4:  heap :190484 (+560)
4:  heap :190488 (+4)
```

Looking good, so I connect my phone to the wifi hotspot it brings up, which oddly is named ESP_04BEF9 and not the `lws-` style ap name suggested in the README. My phone connects to the wifi, pops up the not connected to the internet message. After telling it to stay connected anyway, I navigate to `http://192.168.4.1/factory.html` and see the request on the log:

```
I (16436) wifi: n:6 0, o:6 0, ap:6 1, sta:0 0, prof:6
I (16436) wifi: station: ac:37:43:a3:d9:3f join, AID=1, n, 20
4:  heap :189676 (-808)
4: esp32_lws_fops_open: /ap/factory.html
4:  heap :187020 (-2656)
4:  heap :189048 (+2028)
```
But nothing loads....I wait...still nothing. Sometimes I also get a request for the favicon.ico but nothing.

I then tried connected with a macbook to try and debug the network traffic, same sort of wifi station log appears, but I can't even get the factory.html request to go through this time. Tried connecting from my Windows machine and the wifi immediately disconnects with `Cannot connect to network`.

Something fishy, not sure what, any ideas?

**Comment by lws-team** [comment] 2017-11-07 08:14
I tried this on current factory 3f93751e9eb9266bb5784d6f5b0bfe7184ed8f6a

```
 $ make erase_flash
```

to nuke everything back to scratch. then

```
 $ make flash monitor
```

I was able to connect my wifi to in my case ESP_05D769 (yes I cannot keep up with esp-idf breaking things, it seems to default to that now), an http://192.168.4.1 comes up with the factory page nice and quickly in Firefox 57 and Chrome 64.

**Comment by benjamind** [comment] 2017-11-07 08:18
Mind if I shoot you a copy of my binary files to try flashing tomorrow?
Just to eliminate weirdness in my network, or PC configurations?

Could you also send over the binaries you used so I can do a comparison on
my end? The romfs especially.

**Comment by lws-team** [comment] 2017-11-07 08:23
Sure... you must have a lot right or it can't find the ROMFS.  But make sure it's the same checkout and esp idf is at 0c50b65a34cd6b3954f7435193411a88adb49cb0... with a git submodule update on esp-idf at that checkout

**Comment by lws-team** [comment] 2017-11-07 08:26
[lws-esp32-factory.zip](https://github.com/warmcat/lws-esp32-test-server-demos/files/1449192/lws-esp32-factory.zip)

**Comment by lws-team** [comment] 2017-11-07 08:27
[romfs.img.zip](https://github.com/warmcat/lws-esp32-test-server-demos/files/1449194/romfs.img.zip)

**Comment by benjamind** [comment] 2017-11-07 08:28
Thanks. Away from the PC now but will upload my build tomorrow. Will also
double check my esp-idf versions.

**Comment by benjamind** [comment] 2017-11-10 16:26
Managed to get this to compile under windows 10 and flashed onto the device successfully, with the wifi now coming up and properly delivering pages without issue. So I now have a working Windows build. Will put the PR up this weekend.

My windows PC connection issues were due to the cheap Edimax wifi dongle I believe, I have a better dongle on order and will confirm this is the case before submitting the PR.

**Comment by lws-team** [comment] 2017-11-10 22:19
Well, it isn't that simple to port, so good job.  If there are any dependencies please also mention them in the README.md.  We basically use the esp wlan apis, with the addition of the multi-AP scan state machine on top.  So it shouldn't affect compatibility with the peer OS WLAN at all.

I am in the middle of making some big changes to -factory, but they don't affect the build part.

**Comment by benjamind** [comment] 2017-11-11 06:26
All the changes are actually in the core libwebsockets library in `component.mk` and `contrib/cross-esp32.cmake` this gets the component to compile properly under the `esp-idf` environment. I'll file a PR against this tomorrow with a bit of luck.

The `genromfs` script actually works out of the box under MSYS2. I'll add the additional instructions to the `libwebsockets/READMEs/README.build.md` under the ESP32 section, these are just the steps to install `cmake` under the MSYS2 shell and build `genromfs` from source and add it to the path. 

Actually very minimal changes to make this work under windows which is awesome!

Besides this I think the project could do with a little more instruction on how to customize the factory build for a specific application and how to use the settings from factory in your own application. As I work through the steps myself I'll try and remember to document them and add them in a PR later. Excellent work though, great to see HTTPS working from a microcontroller!

**Comment by lws-team** [comment] 2017-11-11 06:32
Super... it's HTTP/2 too, not just https.

Generally the idea is you just need to change the logo on -factory.  Your actual app will have its own config separately that does whatever you need it to do.  But presumably every app needs a way to set up certs + wlan + updates, so -factory is designed to do that independent of your main app.

**Comment by benjamind** [comment] 2017-11-11 06:51
If it something consumers will see I think it probably needs some simplification, your average user doesn't need to know about certs and updates hopefully. But if its factory only, i.e. consumers never interact with it then that's cool. Do you think we can reduce the ~900kb partition in that case?

**Comment by lws-team** [comment] 2017-11-11 06:55
It's already simplified here; the next version will create its own selfsigned cert at runtime by default.  But I have another feature to integrate before I update it.  If you think it needs to be even more simple after that, well, patches are very welcome.

In the end it will use up its 1MB area and you will have 2.9MB for your app on a typical 4MB serial flash.  But your app simply inherits working certs + wlan ap connection, and a story for updating the app image, to make up for it.

**Comment by lws-team** [comment] 2017-12-10 01:27
FWIW the stuff I mentioned I intended to do is done and pushed a few days ago.

It's also possible to merge the stuff in -factory with your actual app, most of the work for -factory is done by platform-specific stuff and protocols that are actually in lws.

**Closed as completed by lws-team** 2017-12-10 01:27 UTC
